package c24_71_ft_webapp.nexcognifix.domain.boardgame.enums;

public enum GameCategory {
    ATTENTION_TRAINING,
    COGNITIVE_ENHANCEMENT,
    MEMORY_IMPROVEMENT,
    PROCESSING_SPEED,
    LANGUAGE_COMMUNICATION,
    SOCIAL_SKILLS_TRAINING,
    LOGICAL_REASONING,
    MOTOR_COORDINATION,
    CREATIVITY_IMAGINATION
}
